swagger: '2.0'
info:
  title: Security Web API
  version: '1.0'
host: 'localhost:3000'
schemes:
  - http
paths:
  /register:
    post:
      summary: Register a new user
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: The user to create.
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: User registered successfully
        '500':
          description: Error registering user
  /login:
    post:
      summary: Login a user
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: The user to login.
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
        '500':
          description: Error logging in
  /courses:
    get:
      summary: Get assigned courses for the logged in user
      security:
        - Bearer: []
      responses:
        '200':
          description: Successful operation
        '401':
          description: Unauthorized
        '500':
          description: Error getting courses
  /highest-course:
    get:
      summary: Get the highest course for the logged in user
      security:
        - Bearer: []
      responses:
        '200':
          description: Successful operation
        '401':
          description: Unauthorized
        '500':
          description: Error getting highest course
  /lower-course:
    get:
      summary: Get the lower course for the logged in user
      security:
        - Bearer: []
      responses:
        '200':
          description: Successful operation
        '401':
          description: Unauthorized
        '500':
          description: Error getting lower course
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header